"""CRM Enterprise v5.4.0"""
from alembic import op
import sqlalchemy as sa
revision='0005_crm_enterprise'; down_revision='0004_enterprise_user_management'; branch_labels=None; depends_on=None

def upgrade():
 op.create_table('crm_contacts',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('organization_id',sa.Uuid(),sa.ForeignKey('organizations.id',ondelete='CASCADE'),nullable=False),sa.Column('client_id',sa.Uuid(),sa.ForeignKey('clients.id',ondelete='CASCADE')),sa.Column('name',sa.String(200),nullable=False),sa.Column('email',sa.String(320)),sa.Column('phone',sa.String(40)),sa.Column('position',sa.String(120)),sa.Column('notes',sa.Text()),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
 op.create_index('ix_crm_contacts_org','crm_contacts',['organization_id']);op.create_index('ix_crm_contacts_client','crm_contacts',['client_id']);op.create_index('ix_crm_contacts_name','crm_contacts',['name'])
 op.create_table('crm_interactions',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('organization_id',sa.Uuid(),sa.ForeignKey('organizations.id',ondelete='CASCADE'),nullable=False),sa.Column('client_id',sa.Uuid(),sa.ForeignKey('clients.id',ondelete='CASCADE'),nullable=False),sa.Column('user_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='SET NULL')),sa.Column('interaction_type',sa.String(50),nullable=False),sa.Column('subject',sa.String(200),nullable=False),sa.Column('description',sa.Text()),sa.Column('occurred_at',sa.DateTime(timezone=True),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
 op.create_index('ix_crm_interactions_org','crm_interactions',['organization_id']);op.create_index('ix_crm_interactions_client','crm_interactions',['client_id'])
 op.create_table('crm_opportunities',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('organization_id',sa.Uuid(),sa.ForeignKey('organizations.id',ondelete='CASCADE'),nullable=False),sa.Column('client_id',sa.Uuid(),sa.ForeignKey('clients.id',ondelete='CASCADE'),nullable=False),sa.Column('owner_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='SET NULL')),sa.Column('title',sa.String(200),nullable=False),sa.Column('stage',sa.String(50),nullable=False),sa.Column('estimated_value',sa.Float(),nullable=False,server_default='0'),sa.Column('probability',sa.Integer(),nullable=False,server_default='0'),sa.Column('expected_close_date',sa.Date()),sa.Column('notes',sa.Text()),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
 op.create_index('ix_crm_opportunities_org','crm_opportunities',['organization_id']);op.create_index('ix_crm_opportunities_client','crm_opportunities',['client_id']);op.create_index('ix_crm_opportunities_stage','crm_opportunities',['stage'])
 op.create_table('crm_tasks',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('organization_id',sa.Uuid(),sa.ForeignKey('organizations.id',ondelete='CASCADE'),nullable=False),sa.Column('client_id',sa.Uuid(),sa.ForeignKey('clients.id',ondelete='CASCADE')),sa.Column('opportunity_id',sa.Uuid(),sa.ForeignKey('crm_opportunities.id',ondelete='CASCADE')),sa.Column('assigned_to_id',sa.Uuid(),sa.ForeignKey('users.id',ondelete='SET NULL')),sa.Column('title',sa.String(200),nullable=False),sa.Column('description',sa.Text()),sa.Column('status',sa.String(40),nullable=False),sa.Column('priority',sa.String(20),nullable=False),sa.Column('due_at',sa.DateTime(timezone=True)),sa.Column('completed_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
 op.create_index('ix_crm_tasks_org','crm_tasks',['organization_id']);op.create_index('ix_crm_tasks_status','crm_tasks',['status']);op.create_index('ix_crm_tasks_due','crm_tasks',['due_at'])
def downgrade():
 op.drop_table('crm_tasks');op.drop_table('crm_opportunities');op.drop_table('crm_interactions');op.drop_table('crm_contacts')
